import { catenarycloudCoreRules } from "./core.js";
import { catenarycloudTsTypeRules } from "./ts-type.js";
import { catenarycloudWebRules } from "./web.js";

export const catenarycloudRules = {
  ...catenarycloudCoreRules,
  ...catenarycloudWebRules,
  ...catenarycloudTsTypeRules,
};

export const catenarycloudCoreRuleNames = [
  "no-if-statement",
  "no-switch-statement",
  "no-ternary",
  "no-return-null",
  "no-pipe-ladder",
  "no-flatmap-ladder",
  "no-effect-ladder",
  "no-effect-call-in-effect-arg",
  "no-nested-effect-call",
  "no-effect-as",
  "no-effect-wrapper-alias",
  "no-call-tower",
  "no-option-as",
  "no-arrow-ladder",
  "no-branch-in-object",
  "no-iife-wrapper",
  "no-return-in-arrow",
  "no-effect-never",
  "no-effect-async",
  "no-effect-fn-generator",
  "no-effect-sync-console",
  "no-effect-do",
  "no-effect-bind",
  "no-nested-effect-gen",
  "no-runtime-runfork",
  "no-match-void-branch",
  "no-match-effect-branch",
  "warn-effect-sync-wrapper",
  "no-effect-side-effect-wrapper",
  "no-effect-all-step-sequencing",
  "no-effect-orElse-ladder",
  "no-return-in-callback",
  "no-try-catch",
  "no-manual-effect-channels",
  "prevent-dynamic-imports",
] as const;

export const catenarycloudWebRuleNames = [
  "no-react-state",
  "no-render-side-effects",
  "no-atom-registry-effect-sync",
  "no-inline-runtime-provide",
] as const;

export const catenarycloudTsTypeRuleNames = [
  "no-effect-type-alias",
  "no-model-overlay-cast",
  "no-unknown-boolean-coercion-helper",
  "no-fromnullable-nullish-coalesce",
  "no-option-boolean-normalization",
  "no-string-sentinel-return",
  "no-string-sentinel-const",
] as const;

export const catenarycloudFullRuleNames = [
  "no-react-state",
  "no-if-statement",
  "no-switch-statement",
  "no-ternary",
  "no-return-null",
  "no-pipe-ladder",
  "no-flatmap-ladder",
  "no-effect-ladder",
  "no-effect-call-in-effect-arg",
  "no-nested-effect-call",
  "no-effect-as",
  "no-effect-wrapper-alias",
  "no-call-tower",
  "no-option-as",
  "no-arrow-ladder",
  "no-branch-in-object",
  "no-iife-wrapper",
  "no-return-in-arrow",
  "no-atom-registry-effect-sync",
  "no-effect-never",
  "no-effect-type-alias",
  "no-effect-async",
  "no-effect-fn-generator",
  "no-effect-sync-console",
  "no-effect-do",
  "no-effect-bind",
  "no-nested-effect-gen",
  "no-runtime-runfork",
  "no-match-void-branch",
  "no-match-effect-branch",
  "warn-effect-sync-wrapper",
  "no-effect-side-effect-wrapper",
  "no-effect-all-step-sequencing",
  "no-effect-orElse-ladder",
  "no-render-side-effects",
  "no-return-in-callback",
  "no-wrapgraphql-catchall",
  "no-model-overlay-cast",
  "no-unknown-boolean-coercion-helper",
  "no-fromnullable-nullish-coalesce",
  "no-option-boolean-normalization",
  "no-try-catch",
  "no-string-sentinel-return",
  "no-string-sentinel-const",
  "no-manual-effect-channels",
  "prevent-dynamic-imports",
] as const;

export default catenarycloudRules;
